version: '2'

services:
  flight_service:
    build: flightService/.
    links:
      - db
    env_file:
      - 'flightService/.env'
    ports:
      - '8080:6000'

  client:
    build: client/.
    links:
      - managemenet_server
    stdin_open: true
    tty: true

  managemenet_server:
    build: management-app/.
    links:
      - db
    env_file:
      - 'management-app/.env'
    ports:
      - '8000:5000'

  db:
    build: db/.
    image: mysql:5.7.22
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_admin
      MYSQL_PASSWORD: db_admin
      MYSQL_DATABASE: sprc_db

